#Copiado da aula pois o modelo de workflow nao apareceu
name : CI

#Controle do workflow para rodar
on:
  # trigger para push ou pull request
  push:
     branches: [ main ]

  # Permite que você execute o workflow manualmente na guia de ações
  workflow_dispatch:

#Uma execução de workflow é composta de mais trabalhos que podem ser executados sequencialmente ou em paralelo
jobs:
   #Workflow com um unico "build"
   CI:
      #Onde será executado
      runs-on: ubuntu-latest

      #Sequência de tarefas que serão executadas como parte do trabalho
      steps:
        #checkout do repositorio no #GITHUB_WORKSPACE, 
         - uses: actions/checkout@v2

         - name: Setup do nodeJS
           uses: actions/setup-node@v4.0.3
           with:
             node-version: 16.15.1

         - name: Instalação do Mocha para teste
           run: 
                #Entrando no diretorio src e instalando o mocha
                cd src; 
                npm install -g mocha; 
                npm install
         - name: Execução do teste
           run: mocha src/test/convert.js

         #Criação da imagem Docker
         - name: Docker Login
            # You may pin to the exact commit or the version.
            # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
           uses: docker/login-action@v3.3.0
           with:
             username: ${{secrets.DOCKERHUB_USERNAME}}
             password: ${{secrets.DOCKERHUB_PASSWORD}}
                
         - name: Build and push Docker images
           # You may pin to the exact commit or the version.
           # uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85
           uses: docker/build-push-action@v6.7.0
           with:
              context: ./src
              file: ./src/Dockerfile
              push: true
              tags: |
                smsuciu/aula-conversao-temperatura:${{github.run_number}}
                smsuciu/aula-conversao-temperatura:latest
